EPEP = [
    "EXO•SHOOᵀᴱᴿ࿐",
    "÷{k•Πt•£}÷",
    "ツち⻓ムㄚ乙ㄖツ꧂",
    "『Sᶻ』꧁Leona꧂",
    "ᴿᴶˢ࿐ÝѧN尺¡Ķø࿐",
    "『NOB』вαℓα∂σяヅ™",
    "『TG』 ཌĐʀᴀɢᴏƝད°ᴵᴰᴹ°ツ",
    "۝۩ •ZERO• ۩۝",
    "꧁þαšТΣĻ꧂௶ꣷ",
    "『DwR』➻❥Łøvε😍",
    "『APS』•Oscarツ",
    "ঔ•ᗪένιใ⎠° Vɪя͢ʊ͋S͚ •ঔ",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "ST•",
    "『 JW 』•꧁Ivan꧂",
    "『sʜʀᴋ』•ᴮᴬᴰʙᴏʏツ",
    "『ᴹᵛᴸ』Fℓα₥ȏuֆツ",
    "Lᴬ•K o u r u y a m a🌸",
    "{PLN}•JoKeR™",
    "【YWS】 Ꮓϵɾzxᴬᶜ 戈心",
    "꧁ツち⻓ムㄚ乙ㄖツ꧂",
    "✿乂orem࿐⁩",
    "꧁ঔৣ☬☬ঔৣ꧂",
    "꧁▄▄︻̷̿┻̿═━一꧂",
    "GPS×UJANG√",
    "°ᴮᴸᴰ°нυsᴎιツ",
    "꧁Ms. ★๖ۣۜƤriͥภcͣeͫss★꧂",
    "༄ᶦᶰᵈ᭄✿ᴮᴬᴰʙᴏʏツ",
    "Baby•ᴴᵁᴺᵀᴱᴿ࿐",
    "¢єℓ¢ιυѕ",
    "♛Phaňţøm♛",
    "NicK naMe » Leͥgeͣnͫd    ☂️",
    "꧁฿ิีืÅβγ∞ÐθØŁ꧂",
    "INT•ঔৣÐâřҟŦﺂℜêঔৣ",
    "꧁ ༺ HM•GAMING ༻ ꧂",
    "ρнχ•乙ᴮᴬᴰʙᴏʏ乂",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "꧁ ༺ HM•GAMING ༻ ꧂",
    "꧁Ms. ★๖ۣۜƤriͥภcͣeͫss★꧂",
    "ঔ•ᗪένιใ⎠° Vɪя͢ʊ͋S͚ •ঔ",
    "꧁✮ꌗꍏꌩꍏꈤꀘ✮꧂",
    "INT•ঔৣÐâřҟŦﺂℜêঔৣ",
    "༺★BlackSteel★༻",
    "『ᴹᵛᴸ』Fℓα₥ȏuֆツ",
    "꧁●✮CENDEK✮●꧂",
    "꧁✮ꌗꍏꌩꍏꈤꀘ✮꧂",
    "꧁༺༻꧂",
    "꧁༺ɳεאѵαµℓµร☆࿐",
    "《Šûčî|Vāķűm》",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "Ｋｏｋ ｍａｔｉ ｃｕｋ",
    "꧁༺nickname༻꧂",
    "『ηя』M͢A͢S͢_tϵr",
    "꧁฿ิีืÅβγ∞ÐθØŁ꧂",
    "〖₩Ā₩〗 ↬ℳѦδØŊ↫  1  0",
    "『Ｗｏｌｆ』•Ｚｅｒｏツ",
    "▄︻̷̿┻̿═━一ØV₵Ⱨ₳Ɽ₭₳⸕şťªİҝερ",
    "ᴷᴵᴺᴳ°OғB͠a͠r²ツ",
    "꧁ঔৣ☠︎$aπ$❦☠︎ঔৣ꧂",
]

FAKTA = [
    "👀 **Orang yang membayangkan suara baru yang belum pernah didengar, ataumenggabungkan sebuah melodi matanya akan bergerak ke kiri**",
    "👀 **Jika kita terkunci diruang yang kedap udara, kita aka lebih dulu mati keracunan co2 dari pada kekerangan o2**",
    "👀 **Titik merah pada 7-Up logo berasal dari penemunya yang bermata merah. Dia seorang albino.**",
    "👀 **Di Jerman, tahanan yg ingin meloloskan diri dr penjara adl bukan mrupakn perbuatan ilegal. Krn itu salah1 naluri dasar manusia untuk kebebasan.**",
    "👀 **Orang sherpa di Nepal menganjurkan orang memakan bawang putih utk mencegah dan mengobati rasa tidak nyaman yg disebabkan ketinggian gunung.**",
    "👀 **Tanda ’save’ pada Microsoft Office programs menunjukan gambar floppy disk dengan shutter terbalik**",
    "👀 **Ayam yang sudah terpenggal lehernya masih mampu lari sepanjang lapangan bola sebelum benar-benar mati**",
    "👀 **ji apel merupakan racun ringan namun tidak berbahaya bagi manusia**",
    "👀 **Gajah hanya tidur 2 jam dalam sehari**",
    "👀 **Jika lever manusia berhenti bekerja, manusia akan mati dalam 8 samapai 24 jam**",
    "👀 **Kecuali manusia dan monyet, semua mamalia buta warna**",
    "👀 **Orang yang terlalu sering begadang memiliki performa otak seperti 7 tahun lebih tua dari usia aslinya. [dailymail]**",
    "👀 **Ikan mas yang bunting disebut ‘twit’.**",
    "👀 **Pada Usia 3 bulan janin manusia mulai terbentuk sidik jari.**",
    "👀 **Nama paling populer di dunia adalah Muhammad.**",
    "👀 **Seekor cheetah dapat berlari 76 km per jam.**",
    "👀 **Kita bisa mematangkan Mangga dengan cepat dengan cara memasukkan ke dalam paperbag bersama dengan pisang matang.**",
    "👀 **Kulit Zebra adalah putih yang bergaris hitam**",
    "👀 **Di Perancis, jajanan Arum Manis (Rambut Nenek) disebut “Barbe á Papa” yang berarti “Jenggot Ayah”.**",
    "👀 **Darah sama kental dengan air laut**",
    "👀 **Memeluk orang yg disayangi dpt membantu menurunkan tekanan darah, mengurangi stres dan kecemasan, bahkn dpt meningkatkan memori. [Dailymail]**",
    "👀 **Tikus dan kuda tidak bisa muntah**",
    "👀 **Menurut penelitian, pria cenderung menurunkan volume suaranya ketika ia berbicara dg seseorang yg ia cintai, sementara perempuan sebaliknya.**",
    "👀 **Kita bisa mematangkan Mangga dengan cepat dengan cara memasukkan ke dalam paperbag bersama dengan pisang matang.**",
    "👀 **25% kandungan dalam apel adalah Udara. makanya apel bisa mengapung**",
    "👀 **RSVP adalah Respondez s’il Vous Plait yang artinya ‘mohon jawaban’**",
    "👀 **Ada lebih dari 300 bakteri pembentuk karang gigi**",
    "👀 **Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendir**",
    "👀 **Jantung ikan paus biru berdenyut 9 kali dalam semenit**",
    "👀 **Jika lever manusia berhenti bekerja, manusia akan mati dalam 8 samapai 24 jam**",
    "👀 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "👀 **Di Bumi, satu tahun adalah 365 hari. Di planet Merkurius satu tahun adalah 2 hari**",
    "👀 **Sapi tidak punya gigi atas**",
    "👀 **rdiri lama tanpa menekuk lutuk sama sekali akan membuat kita pingsan**",
    "👀 **Kebiasaan sibuk memotret dan mengunggah foto makanan di sosial media, beresiko seseorang menjadi gendut. [Dr. Valerie Taylor]**",
    "👀 **Darah sama kental dengan air laut**",
    "👀 **Orang yang menggunakan tangan kanan, kira-kira, 9 tahun lebih panjang umur dari orang kidal**",
    "👀 **Riset membuktikan, memakan pisang bisa menambah daya ingat**",
    "👀 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "👀 **Kiwi ditetapkan sebagai buah kebangsaan di Cina**",
    "👀 **Kuku ibu jari tumbuh lambat dan kuku jari tengah yang tercepat.**",
    "👀 **Mahluk yang bisa tersipu-sipu hanya manusia**",
    "👀 **Hormon Cinta hanya bertahan 4 tahun, sisanya dorongan seks. [penelitian di University of Mexico]**",
    "👀 **Mengoleskan jeruk nipis dapat mencerahkan bagian lutut / siku yang hitam.**",
    "👀 **Hanya dengan mengurangi brightness dari televisi, anda mampu berhemat lebih dari Rp 1,5 juta setahun. [kompas]**",
    "👀 **Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotorUmur dari capung adalah 24 jam**",
    "👀 **Terdapat hampir 50 jenis kangguru.**",
    "👀 **Tangan kanan orang hidup lebih lama dari tangan kiri.**",
    "👀 **Pulau Giliyang di Sumenep, Jawa Timur disebut sbg pulau “Awet Muda” karena pulau ini memiliki kandungan oksigen terbaik di dunia. [tempo co]**",
    "👀 **Unta punya 3 kelopak mata.**",
    "👀 **Tiga monyet bijak punya nama: Mizaru (See no evil), Mikazaru (Hear no evil), and Mazaru (Speak no evil).**",
    "👀 **Gajah satu-satunya hewan yang tidak bisa meloncat**",
    "👀 **Kuda Nil kentut lewat mulut.**",
    "👀 **Pemogokan cahaya di bumi sekitar 6.000 kali per menit.**",
    "👀 **Di zaman penjajahan Belanda, hukuman orang yg berzina adlh ditangkap dan dicorengkan arang pd hidungnya. Inilah asal usul “Hidung Belang”.**",
    "👀 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "👀 **Perut memproduksi lapisan lendir setiap dua minggu agar perut tidak mencerna organnya sendiri.**",
    "👀 **Tertawa dapat meningkatkan aktivitas antibodi sekitar 20%, juga membantu untuk menghancurkan virus dan sel-sel tumor.**",
    "👀 **makan plum membantu meningkatkan penyerapan zat besi dalam tubuh**",
    "👀 **Ilmu tentang perkembangan apel disebut Pomology**",
    "👀 **Coklat meleleh dalam mulut karena titik lelehnya adalah 35 derajat celcius**",
    "👀 **Venus dan Uranus adalah planet di tata surya kita yang berputar melawan jarum jam. Jadi matahari terbit dari barat di planet ini.**",
    "👀 **13% orang di dunia adalah kidal**",
    "👀 **Jaguar takut pada anjing**",
    "👀 **Pita karet terpanjang adalah di kulkas.**",
    "👀 **Tanduk badak terbuat dari rambutnya yang mengeras**",
    "👀 **Ada sekitar 10ribu jenis apel di dunia Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotor**",
    "👀 **salah satu spesies markisa yang buahnya berwarna ungu bisa melakukan fertilisasi sendiri**",
    "👀 **Kentut sapi termasuk penyebab utama global warming**",
    "👀 **Tikus dan kuda tidak bisa muntah**",
    "👀 **Sekitar 180 juta kartu Valentine tersebar per tahunnya.**",
    "👀 **Telur segar tenggelam diair, telur yang kadaluarsa mengambang**",
    "👀 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "👀 **Jika semua emas dalam laut ditambang, setiap manusia didunia bisa mendapat emas 20 kg masing2.**",
    "👀 **Pria kehilangan 40 helai rambut tiap hari. wanita 70 helai.**",
    "👀 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "👀 **Saat kita bertahan hidup dan tidak ada bahan makanan, sabuk kulit dan sepatu keds adalah makanan terbaik untuk dimakan karena mengandung cukup gizi untuk hidup sementara.**",
    "👀 **Titik diatas huruf i disebut ‘title’**",
    "👀 **Pada abad pertengahan di Eropa, garam sangat mahal harganya, sehingga disebut sebagai “emas putih”.**",
    "👀 **A “jiffy” is the scientific name for 1/100th of a second.**",
    "👀 **Amerika telah memiliki 30,30% bandara di dunia & India hanya 0,70%.**",
    "👀 **Umur dari capung adalah 24 jam**",
    "👀 **Gigi berang-berang tak pernah berhenti tumbuh**",
    "👀 **Lidah seekor Chameleon adalah dua kali panjang tubuhnya sendiri.**",
    "👀 **Eropa adalah benua tanpa padang pasir**",
    "👀 **69% orang Amerika menggunakan internet dan hanya 5,5% dari India.**",
    "👀 **Secara fisik, babi tidak bisa melihat ke langit**",
    "👀 **Pemantik ditemukan sebelum korek api**",
    "👀 **Dry Ice tidak meleleh, tapi menguap**",
    "👀 **Nama Artic (kutub utara) berarti beruang dalam bahasa Yunani (Arktos), dan memang beruang kutub hanya ada di kutub utara**",
    "👀 **Seseorang masih akan sadar selama 8 detik setelah dipenggal**",
    "👀 **Albert Einstein dan Charles Darwin,keduanya menikah dengan sepupu pertama mereka (Elsa Löwenthal dan Emma Wedgewood).**",
    "👀 **98% dari perkosaan dan pembunuhan dilakukan oleh keluarga dekat atau teman korban.**",
    "👀 **Gazzarella adalah keju mozzarella yang terbuat dari susu kucing. 61. Rata-rata orang melihat / mengecek ponselnya sekitar 150 kali sehari. (Laporan Nokia pada MindTrek 2010)**",
    "👀 **Rat-rata orang bergerak 40 kali dalam tidurnya**",
    "👀 **nga pohon markisa adalah Bunga kebangsaan negara Paraguay**",
    "👀 **Topeng tokoh Michael Myers di film horor ‘Helloween’ sebenernya topeng tokoh Captain Kirk (Star Trek) yang di cat putih, karena kurang dana**",
    "👀 **Kucing berkeringat melalui telapak kakinya (terutama saat mendengar gonggongan anjing)**",
    "👀 **Tehnik mengaduk terbaik bukan dengan gerakan memutar, tapi dengan gerakan huruf W**",
    "👀 **Nomer “172? dapat ditemukan pada uang kertas 5 dollar amerika, pada gambar semak-semak dibawah Lincoln Memorial.**",
    "👀 **Shuttlecock untuk badminton harus punya 14 bulu.**",
    "👀 **Memakan seledri membuang kalori lebih banyak dari pada kalori yang terkandung dalam seledri itu sendiri**",
    "👀 **Kulit Plum dipercaya memiliki efek Laxative**",
    "👀 **rung umumnya tidak berkicau apabila mereka hinggap di tanah (Hummingbirdworld).**",
    "👀 **Pendeta Mesir kuno mencabuti setiap helai rambut dan bulu dari badan mereka.**",
    "👀 **Nama asli butterfly (kupu-kupu) adalah flutterby.**",
    "👀 **Dalam setiap inci persegi permukaan smartphone terdapat skitar 25.107 kuman, artinya smartphone lebih kotor dr kloset. [Laporan dr Proporta]**",
    "👀 **Radiasi dari 1 batang rokok sama dgn radiasi 2000x X-ray**",
    "👀 **Tanduk badak terbuat dari rambutnya yang mengeras**",
    "👀 **Kelelawar selalu belok kiri jika terbang keluar gua**",
    "👀 **Ubur-ubur terdiri dari 95% air**",
    "👀 **Riset membuktikan bahwa makan apel bisa mengurangi risiko kena kanker**",
    "👀 **Julius Caesar tewas dengan 23 tikaman**",
    "👀 **Orang yang berusia di atas 100 di AS meningkat dari 4.000 pada tahun 1960 menjadi 55.000 pada tahun 1995.**",
    "👀 **Tidak ada bukti yang pasti siapa yang membangun Taj Mahal.**",
    "👀 **Cahaya matahari mencapai bumi membutuhkan waktu sekitar 8 jam 3 detik.**",
    "👀 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "👀 **Telur segar tenggelam diair, telur yang kadaluarsa mengambang**",
    "👀 **Ken Edwards seorang pria asal Inggris memegang rekor Guinness untuk makan 36 kecoa dalam 1 menit.**",
    "👀 **mangga masih 1 family dengan tanaman Poison Ivy**",
    "👀 **Pisang mengandung vitamin B6 yang bisa mengontrol kadar gula dalam darah, dan membangkitkan mood**",
    "👀 **Microwave ditemukan setelah seorang ilmuan yang berjalan melewati tabung radar mendapati permen coklatnya meleleh disakunya.**",
    "👀 **Hangry adalah penggabungan kata dari “Hungry” dan “Angry”, di pakai ketika anda sedang lapar dan marah.**",
    "👀 **Nama asli butterfly (kupu-kupu) adalah flutterby.**",
    "👀 **Sekitar 14% pecandu yang menggunakan jarum suntik, positif HIV.**",
    "👀 **Karena langkanya logam, piala Oscars yang dibagikan pada perang dunia ke II terbuat dari kayu**",
    "👀 **Ketika kita sedang jatuh cinta, otak akan memproduksi dopamin ekstra, bahan kimia yang membuat seseorang menjadi gembira berlebihan.**",
    "👀 **Merebus telur burung unta butuh waktu 40 menit.**",
    "👀 **Wanita yang sedang stres selama kehamilannya cenderung melahirkan anak-anak yang pemarah. [Institute of Psychiatry, King College London]**",
    "👀 **nanas yang belum matang adalah racun**",
    "👀 **Kucing rumah benci bau lemon dan semua yang berbau sitrus**",
    "👀 **Nama “Gorila” berasal dari kata Yunani “Gorillai” yang berarti “perempuan berbulu”.**",
    "👀 **Hanya 3 malaikat, Gabriel, Michael dan Lucifer yang disebut dalam injil.**",
    "👀 **Air laut di samudra Atlantik lebih asin dari pada di samudra Pasifik**",
    "👀 **gian dalam kulit pisang juga bisa digunakan untuk menghilangkan gatal bekas gigitan nyamuk dengan cara menggosokkannya**",
    "👀 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "👀 **Kode Telephone Internasional untuk Antartica adalah 672.**",
    "👀 **Musik memiliki kemampuan untuk memperbaiki kerusakan otak serta mengembalikan kenangan yang hilang. [cracked .com]**",
    "👀 **25% kandungan dalam apel adalah Udara. makanya apel bisa mengapung**",
    "👀 **ku Guinness Book of Records memegang rekor sebagai buku yang paling banyak dicuri dari perpustakaan**",
    "👀 **Kulit Zebra adalah putih yang bergaris hitam**",
    "👀 **Unta punya 3 kelopak mata.**",
    "👀 **David Sarnoff adalah orang yang menerima sinyal Titanic dan meyelamatkan ratusan nyawa. Dia akhirnya menjadi kepala jaringan radio, the National Broadcasting Company (NBC).**",
    "👀 **pohon kelapa entah kenapa disebut “Tree of Life”**",
    "👀 **Orang yang merasa kesepian memiliki kemungkinan mengalami kepikunan 70-80% lebih tinggi. (Journal of Neurosurgery Neurologi and Psychiatry)**",
    "👀 **Mengunyah permen karet dapat meningkatkan kemampuan berpikir cepat dan kewaspadaan hingga 10 persen. [Jurnal Brain and Cognition]**",
    "👀 **Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendir**",
    "👀 **Hanya dengan mengurangi brightness dari televisi, anda mampu berhemat lebih dari Rp 1,5 juta setahun. [kompas]**",
    "👀 **Orang yang cerdas memiliki kadar seng dan tembaga di rambut mereka**",
]
