name: Code Formatter

on:
  push:
    paths:
    - "**.py"
  workflow_dispatch:

jobs:
  Format_Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"
      - name: Install Formatting Tools
        run: pip install autopep8 autoflake isort black
      - name: Run autopep8 Formatter
        run: |
          autopep8 --verbose --in-place --recursive --aggressive *.py
      - name: Clean Imports
        run: |
          isort .
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .
      - name: Apply Code Formatting
        run: |
          black .
          isort .
      - name: Create Issue
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.TOKEN }}
          title: |
            [${{ github.workflow }}] failed during [${{ github.event_name }}]

          # Auto-assign person who triggered the failure.
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          labels: Skill-Issue, Failure
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - Author: @${{ github.triggering_actor }}
            - Branch: `${{ github.ref }}`
            - Commit: ${{ github.sha }}
            - Workflow Path: `${{ github.workflow_ref }}`
    
            - [ ] **Task**: Bad Code Detected, fix the issue(s), and re-run until successful.
    
            > This issue was created automatically by GitHub, 
            > **DO NOT** close this issue until resolved.
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto Code Fixes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: "github-actions[bot]"
            commit_user_email: "172886759+github-actions[bot]@users.noreply.github.com"
            commit_author: "github-actions[bot] <172886759+github-actions[bot]@users.noreply.github.com>"